version: '2'
services:
    config-service:
        container_name: mydemoapplication
        image: mydemoapplication:latest
        ports:
            - 8080:9080
            - 8085:9085
        depends_on:
           - config-admin
        environment:
          SPRING_APPLICATION_NAME: Service-API-Dev
        networks:
            - spring-admin-network
    config-admin:
        container_name: springbootadmin
        image: myspringbootadmin:latest
        ports:
            - 9060:9060
            - 9065:9065
        networks:
            - spring-admin-network
networks:
    spring-admin-network:
        driver: bridge

